# -*- mode: ruby -*-
# vi: set ft=ruby :

# vm configuration
MEMORY = 2048
CPUS = 2

# docker and compose installer
$script = <<SCRIPT
    #!/bin/bash
    sudo apt-get update
    sudo apt-get dist-upgrade
    wget -qO- https://get.docker.com/ | sudo sh
    sudo systemctl enable docker
    sudo systemctl start docker
    sudo curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > docker-compose && chmod +x docker-compose && sudo mv docker-compose /usr/local/bin/
    sudo curl -L https://raw.githubusercontent.com/docker/compose/1.2.0/contrib/completion/bash/docker-compose > docker-compose && sudo mv docker-compose /etc/bash_completion.d/
    sudo usermod -a -G docker vagrant
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define "docker-1" do |node|
    node.vm.box = "ubuntu/vivid64"
    node.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/vivid/current/vivid-server-cloudimg-amd64-vagrant-disk1.box"
    node.vm.box_check_update = true
    node.vm.network :private_network, ip: "192.168.99.11"
    node.vm.hostname = "docker-1"

    # setup vm
    node.vm.provider "virtualbox" do |v|
      v.name = "docker-1"
      v.memory = MEMORY
      v.cpus = CPUS
    end

    # setup ssh
    node.ssh.insert_key = false
    node.ssh.private_key_path = [ "~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key" ]
    node.vm.provision :file, source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

    # install docker and compose
    node.vm.provision :shell, inline: $script
  end
end
